name: xlingpaper
base: core18
version: '0.1' # '0.1+git'
summary: Produce linguistic documents with multiple outputs from one source document.
description: |
  This is an unofficial package.

  XLingPaper is an add-on to XMLmind XML Editor.

  XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor, having:
  * Extensive DITA 1.3 support, including Lightweight DITA, XDITA, HDITA, MDITA.
  * Extensive DocBook support, including DocBook 5.1 assemblies.
  * Extensive XHTML5 support, including the ability to convert a set of HTML pages (an “ebook”) to EPUB, PDF, Web Help, DOCX, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  xlingpaper:
    command: bin/runxxe8
parts:
  xlingpaper:
    plugin: dump
    source: https://software.sil.org/downloads/r/xlingpaper/XLingPaper-3-9-0XXEPersonalEditionFullSetup.tar.gz
    organize:
      install4xxe8Perso: bin/
      runxxe8: bin/
    build-packages:
      - unzip
    override-build: |
      snapcraftctl build
      install_dir=$PWD
      tar --overwrite -xjf ./XXE8-2Installer.tar
      unzip -oq ./XXE8Installer/xxe-perso-8_2_0.zip -d /opt
      ln -s /opt/xxe-perso-8_2_0/bin/xxe /usr/local/bin
      mkdir -p -m777 /root/.xxe7/addon
      cd /root/.xxe7/addon
      tar --overwrite -xjf ${install_dir}/xlingpaperconfig-xxe7.tar
      mkdir -p -m777 /root/.xxe8/addon
      cd /root/.xxe7/addon
      tar --overwrite -xjf ${install_dir}/xlingpaperconfig-xxe7.tar
      unzip -oq ${install_dir}/XXE8Installer/es_dictionary-8_2_0.zip
      unzip -oq ${install_dir}/XXE8Installer/fr_dictionary-8_2_0.zip
      unzip -oq ${install_dir}/XXE8Installer/fr_translation-8_2_0
      unzip -oq ${install_dir}/XXE8Installer/sample_customize_xxe-8_2_0.zip
      cd $install_dir
      tar --overwrite -xjf ./texlive4xlingpaper.tar -C /opt
      ln -s /opt/texlivexlingpaper/2009/bin/i386-linux /usr/texbinxlingpaper
      cp ./XXE8Installer/preferences.properties /root/.xxe8
      tar --overwrite -xjf $install_dir/XLingPaperSample.tar -C /root/Documents
      LOC="/usr/local/share/applications"
      if [ ! -d $LOC ]; then
        mkdir $LOC
      fi
      echo "[Desktop Entry]">$LOC/XXE.desktop
      echo "Name=XMLmind XML Editor">>$LOC/XXE.desktop
      echo "Comment=Edit XML Data">>$LOC/XXE.desktop
      echo "GenericName=XML Document editor">>$LOC/XXE.desktop
      echo "GenericName[es]=Editor de archivos XML">>$LOC/XXE.desktop
      echo "GenericName[fr]=Editeur de fichiers XML">>$LOC/XXE.desktop
      echo "Exec=xxe %u">>$LOC/XXE.desktop
      echo "Path=/opt/xxe-perso-8_2_0/bin">>$LOC/XXE.desktop
      echo "Icon=/opt/xxe-perso-8_2_0/bin/icon/xxe.ico">>$LOC/XXE.desktop
      echo "MimeType=text/xml;">>$LOC/XXE.desktop
      echo "Terminal=false">>$LOC/XXE.desktop
      echo "Type=Application">>$LOC/XXE.desktop
      echo "Categories=GTK;GNOME;Office;Education">>$LOC/XXE.desktop
      echo "StartupNotify=true">>$LOC/XXE.desktop
      echo "text/xml=XXE.desktop">>$LOC/defaults.list
    stage-packages:
      - openjdk-11-jre-headless
