name: xlingpaper
base: core18
version: '3.9' # '0.1+git'
summary: Produce linguistic documents with multiple outputs from one source document.
description: |
  This is an unofficial package.

  XLingPaper is an add-on to XMLmind XML Editor.

  XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor, having:
  * Extensive DITA 1.3 support, including Lightweight DITA, XDITA, HDITA, MDITA.
  * Extensive DocBook support, including DocBook 5.1 assemblies.
  * Extensive XHTML5 support, including the ability to convert a set of HTML pages (an “ebook”) to EPUB, PDF, Web Help, DOCX, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
layout:
  /opt/texlivexlingpaper2020/bin/x86_64-linux:
    symlink: $SNAP/usr/texbinxlingpaper2020
  # Fix resource relocation problem of zenity part
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity

apps:
  xlingpaper:
    command: bin/xlingpaper-wrapper.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
      XXE_PREFS_DIR: $SNAP_USER_DATA/config
    extensions:
      - gnome-3-28
    plugs:
      - cups-control
      - home
      - network
      - removable-media

parts:
  wrapper:
    plugin: dump
    source: scripts
    organize:
      xlingpaper-wrapper.sh: bin/xlingpaper-wrapper.sh

  xlingpaper:
    plugin: dump
    source: https://software.sil.org/downloads/r/xlingpaper/XLingPaper-3-9-0XXEPersonalEditionFullSetup.tar.gz
    filesets:
      excluded-tarballs:
        - -*.tar
      excluded-xxe-scripts:
        - -runxxe*
        - -install4xxe*
    build-packages:
      - unzip
    override-build: |
      snapcraftctl build
      # Part 1/6: Accept license: Handled by xlingpaper-wrapper.sh.

      # Part 2/6: Install XXE Personal.
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/XXE8-2Installer.tar
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/xxe-perso-8_2_0.zip -d $SNAPCRAFT_PART_INSTALL/opt

      # Part 3/6: Install XLingPaper config files.
      xxe_base=$SNAPCRAFT_PART_INSTALL/opt/xxe-perso-8_2_0
      addons=${xxe_base}/addon
      mkdir -p -m777 "$addons"
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/xlingpaperconfig-xxe7.tar -C $addons
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/es_dictionary-8_2_0.zip -d $addons
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/fr_dictionary-8_2_0.zip -d $addons
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/fr_translation-8_2_0 -d $addons
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/sample_customize_xxe-8_2_0.zip -d $addons

      # Part 4/6: Install texlive for XLingPaper: 64-bit version installed in own part.
      # tar --overwrite -xzf $SNAPCRAFT_PART_BUILD/texlive4xlingpaper.tar -C $SNAPCRAFT_PART_INSTALL/opt

      # Part 5/6: Install XXE preferences: Handled by partly by xlingpaper-wrapper.sh.
      configs=${xxe_base}/config
      mkdir -p -m777 "$configs"
      cp $SNAPCRAFT_PART_BUILD/XXE8Installer/preferences.properties $configs

      # Part 6/6: Install sample XLingPaper document.
      mkdir -p -m777 ${xxe_base}/examples
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/XLingPaperSample.tar -C ${xxe_base}/examples
      echo "text/xml=xxe.desktop" >> $SNAPCRAFT_PART_INSTALL/usr/share/applications/defaults.list
    organize:
      # XXE8Installer/preferences.properties: opt/xxe-perso-8_2_0/config/
      opt/xxe-perso-8_2_0/examples/My_XLingPaper/SamplePaper.xml: opt/xxe-perso-8_2_0/examples/
      XXEPersonalAndXLingPaperLicense.txt: opt/xxe-perso-8_2_0/
    stage:
      - $excluded-tarballs
      - $excluded-xxe-scripts
      - XXE8Installer/preferences.properties
      - -opt/xxe-perso-8_2_0/examples/My_XLingPaper
    stage-packages:
      - gedit
      - openjdk-11-jre

  # https://software.sil.org/xlingpaper/xelatex-package-from-tex-live-2020/
  texbin2020: # probably needed eventually
    plugin: dump
    source: http://software.sil.org/downloads/r/xlingpaper/resources/xelatex-upgrade/XeLaTeX2020Installer.tar.gz
    override-build: |
      snapcraftctl build
      mkdir -p -m777 $SNAPCRAFT_PART_INSTALL/opt
      tar --overwrite -xzf $SNAPCRAFT_PART_INSTALL/texlivexlingpaper2020.tar -C $SNAPCRAFT_PART_INSTALL/opt

  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity:
    plugin: nil
    stage-packages:
      - zenity
    prime:
      - usr/bin/zenity
      - usr/share/zenity/*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup: # very slow, ~2 or 3 min.
    after:
      - texbin2020
      - wrapper
      - xlingpaper
      - zenity
    plugin: nil
    filesets:
      excluded:
        - -*.tar*
        - -*.zip
    stage:
      - $excluded
    build-snaps: [core18, gnome-3-28-1804]
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
