name: xlingpaper
base: core18
version: '0.1' # '0.1+git'
summary: Produce linguistic documents with multiple outputs from one source document.
description: |
  This is an unofficial package.

  XLingPaper is an add-on to XMLmind XML Editor.

  XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor, having:
  * Extensive DITA 1.3 support, including Lightweight DITA, XDITA, HDITA, MDITA.
  * Extensive DocBook support, including DocBook 5.1 assemblies.
  * Extensive XHTML5 support, including the ability to convert a set of HTML pages (an “ebook”) to EPUB, PDF, Web Help, DOCX, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
layout:
  /opt/xxe-perso-8_2_0/bin/xxe:
    symlink: $SNAP/opt
  /opt/texlivexlingpaper/2009/bin/i386-linux:
    symlink: $SNAP/usr/texbinxlingpaper

apps:
  xlingpaper:
    command: opt/xxe-perso-8_2_0/bin/xxe
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    extensions:
      - gnome-3-28
    plugs:
      - home

parts:
  xlingpaper:
    plugin: dump
    source: https://software.sil.org/downloads/r/xlingpaper/XLingPaper-3-9-0XXEPersonalEditionFullSetup.tar.gz
    organize:
      XXE8Installer/preferences.properties: $SNAPCRAFT_PART_INSTALL/root/.xxe8
      data/xxe.desktop: $SNAPCRAFT_PART_INSTALL/usr/share/applications
      data/xlingpaper.desktop: $SNAPCRAFT_PART_INSTALL/usr/share/applications
    filesets:
      excluded-tarballs:
        - -*.tar
      excluded-xxe-scripts:
        - -runxxe*
        - -install4xxe*
    build-packages:
      - unzip
    override-build: |
      snapcraftctl build
      # Part 1/6: Accept license.
      # TODO at first run of app with a wrapper script & control file.
      # Part 2/6: Install XXE Personal.
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/XXE8-2Installer.tar
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/xxe-perso-8_2_0.zip -d $SNAPCRAFT_PART_INSTALL/opt
      # Part 3/6: Install XLingPaper config files.
      # ln -sf /opt/xxe-perso-8_2_0/bin/xxe ${SNAP}/bin
      mkdir -p -m777 $SNAPCRAFT_PART_INSTALL/root/.xxe7/addon
      # cd /root/.xxe7/addon
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/xlingpaperconfig-xxe7.tar -C $SNAPCRAFT_PART_INSTALL/root/.xxe7/addon
      mkdir -p -m777 $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      # cd /root/.xxe7/addon
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/xlingpaperconfig-xxe7.tar -C $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/es_dictionary-8_2_0.zip -d $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/fr_dictionary-8_2_0.zip -d $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/fr_translation-8_2_0 -d $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      unzip -oq $SNAPCRAFT_PART_BUILD/XXE8Installer/sample_customize_xxe-8_2_0.zip -d $SNAPCRAFT_PART_INSTALL/root/.xxe8/addon
      # Part 4/6: Install texlive for XLingPaper.
      # cd $SNAPCRAFT_PART_BUILD
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      tar --overwrite -xzf $SNAPCRAFT_PART_BUILD/texlive4xlingpaper.tar -C $SNAPCRAFT_PART_INSTALL/opt
      # ln -sf /opt/texlivexlingpaper/2009/bin/i386-linux $SNAPCRAFT_PART_INSTALL/usr/texbinxlingpaper
      # Part 5/6: Install XXE preferences.
      # cp $SNAPCRAFT_PART_BUILD/XXE8Installer/preferences.properties $SNAPCRAFT_PART_INSTALL/root/.xxe8
      # Part 6/6: Install sample XLingPaper document.
      mkdir -p -m777 $SNAPCRAFT_PART_INSTALL/root/Documents
      tar --overwrite -xjf $SNAPCRAFT_PART_BUILD/XLingPaperSample.tar -C $SNAPCRAFT_PART_INSTALL/root/Documents
      LOC=$SNAPCRAFT_PART_INSTALL/usr/local/share/applications
      # mkdir -p $LOC
      # echo "[Desktop Entry]" > $LOC/XXE.desktop
      # echo "Name=XMLmind XML Editor" >> $LOC/XXE.desktop
      # echo "Comment=Edit XML Data" >> $LOC/XXE.desktop
      # echo "GenericName=XML Document editor" >> $LOC/XXE.desktop
      # echo "GenericName[es]=Editor de archivos XML" >> $LOC/XXE.desktop
      # echo "GenericName[fr]=Editeur de fichiers XML" >> $LOC/XXE.desktop
      # echo "Exec=xxe %u" >> $LOC/XXE.desktop
      # echo "Path=/opt/xxe-perso-8_2_0/bin" >> $LOC/XXE.desktop
      # echo "Icon=/opt/xxe-perso-8_2_0/bin/icon/xxe.ico" >> $LOC/XXE.desktop
      # echo "MimeType=text/xml;" >> $LOC/XXE.desktop
      # echo "Terminal=false" >> $LOC/XXE.desktop
      # echo "Type=Application" >> $LOC/XXE.desktop
      # echo "Categories=GTK;GNOME;Office;Education" >> $LOC/XXE.desktop
      # echo "StartupNotify=true" >> $LOC/XXE.desktop
      echo "text/xml=xxe.desktop" >> $SNAPCRAFT_PART_INSTALL/usr/share/applications/defaults.list
    stage:
      - $excluded-tarballs
      - $excluded-xxe-scripts
    stage-packages:
      - openjdk-11-jre
