name: xlingpaper
base: core18
version: '0.1+git'
summary: Produce linguistic documents with multiple outputs from one source document.
description: |
  This is an unofficial package.

  XLingPaper is an add-on to XMLmind XML Editor.

  XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor, having:
  * Extensive DITA 1.3 support, including Lightweight DITA, XDITA, HDITA, MDITA.
  * Extensive DocBook support, including DocBook 5.1 assemblies.
  * Extensive XHTML5 support, including the ability to convert a set of HTML pages (an “ebook”) to EPUB, PDF, Web Help, DOCX, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  xlingpaper:
    command: bin/runxxe8
parts:
  xlingpaper:
    plugin: dump
    source: https://software.sil.org/downloads/r/xlingpaper/XLingPaper-3-9-0XXEPersonalEditionFullSetup.tar.gz
    organize:
      install4xxe8Perso: bin/
      runxxe8: bin/
    override-stage: |
      sed -r 's/^(less.*)$/# \1/' bin/install4xxe8Perso
    override-prime: |
      snapcraftctl prime
      echo -e '\ny\n' | install4xxe8Perso
