name: xmlmind-xml-editor
base: core18
version: '0.1+git'
summary: XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor
description: |
  This is an unofficial package.

  XMLmind XML Editor is a strictly validating, near WYSIWYG, XML editor, having:
  * Extensive DITA 1.3 support, including Lightweight DITA, XDITA, HDITA, MDITA.
  * Extensive DocBook support, including DocBook 5.1 assemblies.
  * Extensive XHTML5 support, including the ability to convert a set of HTML pages (an “ebook”) to EPUB, PDF, Web Help, DOCX, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  xlingpaper:
    source: https://software.sil.org/downloads/r/xlingpaper/XLingPaper-3-9-0XXEPersonalEditionFullSetup.tar.gz
    plugin: dump
