#!/bin/sh

# Install hook for xlingpaper. Only runs once at initial installation.

# Mark 1st_run.
touch "${SNAP_USER_DATA}/1st_run"

xxe_dir="${SNAP}/opt/xxe-perso-8_2_0"
eula='XXEPersonalAndXLingPaperLicense.txt'

# Ensure EULA in SNAP_USER_DATA.
if [ ! -f "${SNAP_USER_DATA}/${eula}" ]; then
    cp "${xxe_dir}/${eula}" "${SNAP_USER_DATA}/${eula}"
fi

# Ensure default preferences are set.
user_prefs="${SNAP_USER_DATA}/config/preferences.properties"
if [ ! -f "$user_prefs" ]; then
    mkdir -p "${SNAP_USER_DATA}/config"
    cp "${xxe_dir}/config/preferences.properties" "$user_prefs"
fi

# Copy examples into user data.
example_file="${SNAP_USER_DATA}/examples/SamplePaper.xml"
if [ ! -f "$example_file" ]; then
    mkdir -p "${SNAP_USER_DATA}/examples"
    cp "${xxe_dir}/examples/SamplePaper.xml" "$example_file"
fi
